// <auto-generated />
using System;
using KeyKeep.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KeyKeep.Data.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    [Migration("20230614163847_RemoveUserFromCryptKey")]
    partial class RemoveUserFromCryptKey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("KeyKeep.Data.Entities.CryptKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("KeyValue")
                        .HasColumnType("BLOB");

                    b.Property<int?>("PasswordId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PasswordId");

                    b.ToTable("CryptKeys");
                });

            modelBuilder.Entity("KeyKeep.Data.Entities.Password", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("URL")
                        .HasColumnType("BLOB");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("UserName")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("UserPassword")
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Passwords");
                });

            modelBuilder.Entity("KeyKeep.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Email")
                        .HasColumnType("BLOB");

                    b.Property<string>("FirstName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("LoginPassword")
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("KeyKeep.Data.Entities.CryptKey", b =>
                {
                    b.HasOne("KeyKeep.Data.Entities.Password", "Password")
                        .WithMany("CryptKeys")
                        .HasForeignKey("PasswordId");

                    b.Navigation("Password");
                });

            modelBuilder.Entity("KeyKeep.Data.Entities.Password", b =>
                {
                    b.HasOne("KeyKeep.Data.Entities.User", "User")
                        .WithMany("Passwords")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("KeyKeep.Data.Entities.Password", b =>
                {
                    b.Navigation("CryptKeys");
                });

            modelBuilder.Entity("KeyKeep.Data.Entities.User", b =>
                {
                    b.Navigation("Passwords");
                });
#pragma warning restore 612, 618
        }
    }
}
